CREATE TABLE User (
     id VARCHAR(36) PRIMARY KEY,
     email VARCHAR(120) UNIQUE NOT NULL,
     password VARCHAR(128) NOT NULL,
     is_admin BOOLEAN DEFAULT FALSE,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
 );